G21 CRUZ CRESPO, IGNACIO DE LA GÓMEZ CORTÉS, SERGIO JOSÉ

In [135]:
import numpy as np
from sklearn.cluster import KMeans
from sklearn.cluster import AgglomerativeClustering
from sklearn.metrics import davies_bouldin_score
from sklearn.datasets.samples_generator import make_blobs
import matplotlib as mpl
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap
import csv
import pandas as pd


df = pd.read_csv('Countries.csv')

In [136]:
df

,Country,Region,Population,Area (sq. mi.),Pop. Density (per sq. mi.),Coastline (coast/area ratio),Net migration,Infant mortality (per 1000 births),GDP (USD per capita),Literacy (%),Phones (per 1000),Arable (%),Crops (%),Other (%),Climate,Birthrate,Deathrate,Agriculture,Industry,Service
0,Afghanistan,ASIA (EX. NEAR EAST),31056997,647500,48.0,0.00,23.06,163.07,700.0,36.0,3.2,12.13,0.22,87.65,1.0,46.60,20.34,0.380,0.240,0.380
1,Albania,EASTERN EUROPE,3581655,28748,124.6,1.26,-4.93,21.52,4500.0,86.5,71.2,21.09,4.42,74.49,3.0,15.11,5.22,0.232,0.188,0.579
2,Algeria,NORTHERN AFRICA,32930091,2381740,13.8,0.04,-0.39,31.00,6000.0,70.0,78.1,3.22,0.25,96.53,1.0,17.14,4.61,0.101,0.600,0.298
3,American Samoa,OCEANIA,57794,199,290.4,58.29,-20.71,9.27,8000.0,97.0,259.5,10.00,15.00,75.00,2.0,22.46,3.27,NaN,NaN,NaN
4,Andorra,WESTERN EUROPE,71201,468,152.1,0.00,6.60,4.05,19000.0,100.0,497.2,2.22,0.00,97.78,3.0,8.71,6.25,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
222,West Bank,NEAR EAST,2460492,5860,419.9,0.00,2.98,19.62,800.0,NaN,145.2,16.90,18.97,64.13,3.0,31.67,3.92,0.090,0.280,0.630
223,Western Sahara,NORTHERN AFRICA,273008,266000,1.0,0.42,NaN,NaN,NaN,NaN,NaN,0.02,0.00,99.98,1.0,NaN,NaN,NaN,NaN,0.400
224,Yemen,NEAR EAST,21456188,527970,40.6,0.36,0.00,61.50,800.0,50.2,37.2,2.78,0.24,96.98,1.0,42.89,8.30,0.135,0.472,0.393
225,Zambia,SUB-SAHARAN AFRICA,11502010,752614,15.3,0.00,0.00,88.29,800.0,80.6,8.2,7.08,0.03,92.90,2.0,41.00,19.93,0.220,0.290,0.489
226,Zimbabwe,SUB-SAHARAN AFRICA,12236805,390580,31.3,0.00,0.00,67.69,1900.0,90.7,26.8,8.32,0.34,91.34,2.0,28.01,21.84,0.179,0.243,0.579

In [139]:
df = df.drop([223])
df = df.drop('Region',axis = 1)
df = df.drop('Country',axis = 1)

1. El conjunto de datos incluye las variables de los datos (Country,Population,etc/) del archivo countries, eliminando la variable 'region' que no usaremos
Describe las principales propiedades de cada pais
Se muestra a continuación la tabla con el nombre, el tipo y la tabla de estadísticos descriptivos

In [140]:
df

,Population,Area (sq. mi.),Pop. Density (per sq. mi.),Coastline (coast/area ratio),Net migration,Infant mortality (per 1000 births),GDP (USD per capita),Literacy (%),Phones (per 1000),Arable (%),Crops (%),Other (%),Climate,Birthrate,Deathrate,Agriculture,Industry,Service
0,31056997,647500,48.0,0.00,23.06,163.07,700.0,36.0,3.2,12.13,0.22,87.65,1.0,46.60,20.34,0.380,0.240,0.380
1,3581655,28748,124.6,1.26,-4.93,21.52,4500.0,86.5,71.2,21.09,4.42,74.49,3.0,15.11,5.22,0.232,0.188,0.579
2,32930091,2381740,13.8,0.04,-0.39,31.00,6000.0,70.0,78.1,3.22,0.25,96.53,1.0,17.14,4.61,0.101,0.600,0.298
3,57794,199,290.4,58.29,-20.71,9.27,8000.0,97.0,259.5,10.00,15.00,75.00,2.0,22.46,3.27,NaN,NaN,NaN
4,71201,468,152.1,0.00,6.60,4.05,19000.0,100.0,497.2,2.22,0.00,97.78,3.0,8.71,6.25,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
221,16025,274,58.5,47.08,NaN,NaN,3700.0,50.0,118.6,5.00,25.00,70.00,2.0,NaN,NaN,NaN,NaN,NaN
222,2460492,5860,419.9,0.00,2.98,19.62,800.0,NaN,145.2,16.90,18.97,64.13,3.0,31.67,3.92,0.090,0.280,0.630
224,21456188,527970,40.6,0.36,0.00,61.50,800.0,50.2,37.2,2.78,0.24,96.98,1.0,42.89,8.30,0.135,0.472,0.393
225,11502010,752614,15.3,0.00,0.00,88.29,800.0,80.6,8.2,7.08,0.03,92.90,2.0,41.00,19.93,0.220,0.290,0.489
226,12236805,390580,31.3,0.00,0.00,67.69,1900.0,90.7,26.8,8.32,0.34,91.34,2.0,28.01,21.84,0.179,0.243,0.579

In [141]:
df.dtypes

Population                              int64
Area (sq. mi.)                          int64
Pop. Density (per sq. mi.)            float64
Coastline (coast/area ratio)          float64
Net migration                         float64
Infant mortality (per 1000 births)    float64
GDP (USD per capita)                  float64
Literacy (%)                          float64
Phones (per 1000)                     float64
Arable (%)                            float64
Crops (%)                             float64
Other (%)                             float64
Climate                               float64
Birthrate                             float64
Deathrate                             float64
Agriculture                           float64
Industry                              float64
Service                               float64
dtype: object

In [142]:
df.describe()

,Population,Area (sq. mi.),Pop. Density (per sq. mi.),Coastline (coast/area ratio),Net migration,Infant mortality (per 1000 births),GDP (USD per capita),Literacy (%),Phones (per 1000),Arable (%),Crops (%),Other (%),Climate,Birthrate,Deathrate,Agriculture,Industry,Service
count,2.260000e+02,2.260000e+02,226.000000,226.000000,224.000000,224.000000,226.000000,209.000000,223.000000,224.000000,224.000000,224.000000,204.000000,224.000000,223.000000,212.000000,211.000000,211.000000
mean,2.886625e+07,5.996970e+05,380.719912,21.257124,0.038125,35.506964,9689.823009,82.838278,236.061435,13.858616,4.584598,81.556429,2.144608,22.114732,9.241345,0.150844,0.282711,0.566066
std,1.181377e+08,1.794119e+06,1663.679301,72.434062,4.889269,35.389899,10049.138513,19.722173,227.991829,13.036859,8.374596,16.130080,0.696522,11.176716,4.990026,0.146798,0.138272,0.165842
min,7.026000e+03,2.000000e+00,0.000000,0.000000,-20.990000,2.290000,500.000000,17.600000,0.200000,0.000000,0.000000,33.330000,1.000000,7.290000,2.290000,0.000000,0.020000,0.062000
25%,4.425318e+05,4.407250e+03,29.725000,0.100000,-0.927500,8.150000,1900.000000,70.600000,37.800000,3.460000,0.190000,71.552500,2.000000,12.672500,5.910000,0.037750,0.193000,0.433000
50%,4.914957e+06,8.523500e+04,79.150000,0.760000,0.000000,21.000000,5550.000000,92.500000,176.200000,10.475000,1.055000,85.540000,2.000000,18.790000,7.840000,0.099000,0.272000,0.573000
75%,1.757631e+07,4.441805e+05,190.975000,10.357500,0.997500,55.705000,15700.000000,98.000000,389.650000,20.000000,4.467500,95.125000,3.000000,29.820000,10.605000,0.221000,0.341000,0.679000
max,1.313974e+09,1.707520e+07,16271.500000,870.660000,23.060000,191.190000,55100.000000,100.000000,1035.600000,62.110000,50.680000,100.000000,4.000000,50.730000,29.740000,0.769000,0.906000,0.954000

Por ejemplo es trivial ver que hay una relación clara entre la alfabetización y el USD per capita (dinero) y los cultivos con 
la cantidad de terreno arable

In [143]:
#La correlacion de GDP con el resto de variables
df.corr().loc[:,['GDP (USD per capita)']]

                                    GDP (USD per capita)
Population                                     -0.039324
Area (sq. mi.)                                  0.072185
Pop. Density (per sq. mi.)                      0.195773
Coastline (coast/area ratio)                    0.049118
Net migration                                   0.382461
Infant mortality (per 1000 births)             -0.600774
GDP (USD per capita)                            1.000000
Literacy (%)                                    0.513144
Phones (per 1000)                               0.834499
Arable (%)                                      0.019768
Crops (%)                                      -0.219229
Other (%)                                       0.097828
Climate                                         0.340791
Birthrate                                      -0.650137
Deathrate                                      -0.201661
Agriculture                                    -0.586769
Industry                                       -0.028926
Service                                         0.550216

Se ve una relación amplia con los valores que se aproximan mas a -1 o a 1

Nuestro criterio para filtrar variables con poca relación es que se encuentren entre los valores (-0,5 / 0,5)

Normalizamos las variables puesto que algunas estan en escala de millones y otras en escala de miles

In [144]:
from sklearn.preprocessing import StandardScaler

# Normalizamos los datos con StardardScaler que resta a cada variable su media y la divide
# entre su desviación típica.
# Otra opción sería usar MinMaxScaler que cambia el rango de la variable al intervalo [0,1]
scaler = StandardScaler()
scaler.fit(df)
df_scaled =scaler.transform(df)
df_scaled = pd.DataFrame(df_scaled, columns = df.columns)

df_scaled['target']=df_scaled['GDP (USD per capita)']
#df_scaled.describe()
# Transformamos las variables de entrada
df_scaled

,Population,Area (sq. mi.),Pop. Density (per sq. mi.),Coastline (coast/area ratio),Net migration,Infant mortality (per 1000 births),GDP (USD per capita),Literacy (%),Phones (per 1000),Arable (%),Crops (%),Other (%),Climate,Birthrate,Deathrate,Agriculture,Industry,Service,target
0,0.018585,0.026703,-0.200434,-0.294120,4.719199,3.612577,-0.896572,-2.380607,-1.023656,-0.132891,-0.522338,0.378623,-1.647361,2.195646,2.229171,1.564722,-0.309625,-1.124619,-0.896572
1,-0.214502,-0.318940,-0.154290,-0.276686,-1.018404,-0.396110,-0.517591,0.186111,-0.724729,0.555930,-0.019698,-0.439071,1.231111,-0.628129,-0.807690,0.554148,-0.686589,0.078173,-0.517591
2,0.034476,0.995474,-0.221037,-0.293567,-0.087760,-0.127637,-0.367993,-0.652519,-0.694397,-0.817869,-0.518748,0.930380,-1.647361,-0.446095,-0.930208,-0.340347,2.300127,-1.620242,-0.367993
3,-0.244396,-0.334888,-0.054410,0.512398,-4.253109,-0.743029,-0.168529,0.719785,0.103036,-0.296640,1.246475,-0.407383,-0.208125,0.030961,-1.199348,NaN,NaN,NaN,-0.168529
4,-0.244282,-0.334738,-0.137723,-0.294120,1.345103,-0.890859,0.928522,0.872263,1.147962,-0.894746,-0.548667,1.008049,1.231111,-1.202031,-0.600813,NaN,NaN,NaN,0.928522
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
221,-0.244750,-0.334846,-0.194109,0.357293,NaN,NaN,-0.597376,-1.669041,-0.516359,-0.681027,2.443237,-0.718057,-0.208125,NaN,NaN,NaN,NaN,NaN,-0.597376
222,-0.224013,-0.331726,0.023603,-0.294120,0.603048,-0.449918,-0.886599,NaN,-0.399426,0.233814,1.721590,-1.082788,1.231111,0.856841,-1.068795,-0.415458,-0.019652,0.386427,-0.886599
223,-0.062863,-0.040068,-0.204892,-0.289139,-0.007815,0.736121,-0.886599,-1.658876,-0.874193,-0.851695,-0.519945,0.958341,-1.647361,1.862962,-0.189070,-0.108188,1.372215,-1.046045,-0.886599
224,-0.147309,0.085422,-0.220133,-0.294120,-0.007815,1.494812,-0.886599,-0.113763,-1.001677,-0.521122,-0.545077,0.704831,-0.208125,1.693482,2.146823,0.472209,0.052841,-0.465803,-0.886599
225,-0.141076,-0.116816,-0.210495,-0.294120,-0.007815,0.911421,-0.776894,0.399581,-0.919911,-0.425794,-0.507977,0.607900,-0.208125,0.528641,2.530447,0.192253,-0.287877,0.078173,-0.776894

In [146]:
from sklearn.neural_network import MLPRegressor
from sklearn.model_selection import cross_val_score
from sklearn.metrics import mean_squared_error
import numpy as np


regul_param_range = 10.0 ** -np.arange(1, 7) 

cv_scores_mean=[]
cv_scores_std=[]

for regul_param in regul_param_range:
    # aumentamos el parámetro max_iter hasta que converja
    mlp=MLPRegressor(hidden_layer_sizes=(200,1 ), activation='relu', solver='adam', alpha=regul_param, batch_size=100, 
             learning_rate='constant', learning_rate_init=0.001, max_iter=350, random_state=333)
    mlp2=MLPRegressor(hidden_layer_sizes=(50,2 ), activation='relu', solver='adam', alpha=regul_param, batch_size=100, 
             learning_rate='constant', learning_rate_init=0.001, max_iter=350, random_state=333)
    
    # El error es neg_mean_squared_error el MSE en negativo!! Más pequeño peor.
    scores = cross_val_score(mlp, df_scaled, df_scaled.target.ravel(), cv=5, scoring='neg_mean_squared_error')
    
    cv_scores_mean.append(scores.mean())
    cv_scores_std.append(scores.std())

C:\Users\ignac\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:530: FutureWarning: From version 0.22, errors during fit will result in a cross validation score of NaN by default. Use error_score='raise' if you want an exception raised or error_score=np.nan to adopt the behavior from version 0.22.
  FutureWarning)

ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

In [ ]:
import matplotlib.pyplot as plt

# Dibujamos la línea de la exactitud media en las partes de test
# Como el 
plt.plot(np.log10(regul_param_range), cv_scores_mean, color="g", label="Test")

# Dibujamos la banda de la desviación típica
lower_limit=np.array(cv_scores_mean)-np.array(cv_scores_std)
upper_limit=np.array(cv_scores_mean)+np.array(cv_scores_std)
plt.fill_between(np.log10(regul_param_range), lower_limit, upper_limit, color="#DDDDDD")

# Creamos el gráfico
plt.title("Curva de aprendizaje")
plt.xlabel("Regularización 10^{-X}"), plt.ylabel("negative MSE"), plt.legend(loc="best")
plt.tight_layout()
plt.show()

#Hemos intentado construir los 2 perceptrones con los parametros que pedian en la practica pero al construirlo llega a un valor NaN que no entendemos donde esta